apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-app
  template:
    metadata:
      labels:
        app: ledger-app
    spec:
      containers:
        - name: ledger-app
          image: runtesting/ledger:${IMAGE_TAG}
          ports:
            - containerPort: 8000
